/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: juancastrog1 (https://sketchfab.com/juancastrog1)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pendulum-fa12a8bd03e146eda6e0e45da898097d
Title: PENDULUM
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, useAnimations, Environment } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type PenduProps = {
    position: [number, number, number];
    rotation: [number, number, number];
    scale: number;
}


type GLTFResult = GLTF & {
  nodes: {
    pSphere9_azul2_0: THREE.Mesh
    pTorus8_base_cromogris_0: THREE.Mesh
    pSphere16_rosa_0: THREE.Mesh
    pSphere11_rosa_0: THREE.Mesh
    pSphere15_azul2_0: THREE.Mesh
    pTorus6_base_cromogris_0: THREE.Mesh
    pSphere10_azul_0: THREE.Mesh
    pSphere13_azul2_0: THREE.Mesh
    pSphere18_rosa_0: THREE.Mesh
    pTorus5_base_cromogris_0: THREE.Mesh
    pSphere17_azul2_0: THREE.Mesh
    pSphere12_azul_0: THREE.Mesh
    pSphere14_rosa_0: THREE.Mesh
    pTorus9_base_cromogris_0: THREE.Mesh
    pCylinder5_base_cromogris_0: THREE.Mesh
    pTorus10_base_cromogris_0: THREE.Mesh
    pSphere19_base_cromogris_0: THREE.Mesh
    pCylinder9_base_cromogris_0: THREE.Mesh
    pPipe1_base_cromogris_0: THREE.Mesh
    pCylinder10_base_cromogris_0: THREE.Mesh
    pPipe2_base_cromogris_0: THREE.Mesh
    pSphere20_base_cromogris_0: THREE.Mesh
    pCylinder13_lambert1_0: THREE.Mesh
    pCylinder14_lambert1_0: THREE.Mesh
  }
  materials: {
    azul2: THREE.MeshStandardMaterial
    base_cromogris: THREE.MeshStandardMaterial
    rosa: THREE.MeshStandardMaterial
    azul: THREE.MeshStandardMaterial
    lambert1: THREE.MeshStandardMaterial
  }
}

type ActionName = 'Take 001'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

export function Pendu({position, rotation, scale}: PenduProps) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials } = useGLTF('/pendulum.gltf') as GLTFResult

  return (
    <group dispose={null} position={position} rotation={rotation} scale={scale}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="1460ccfda89e4dd5a93ef6862d8e1a90fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="pSphere9">
                  <mesh
                    name="pSphere9_azul2_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pSphere9_azul2_0.geometry}
                    material={materials.azul2}
                  />
                </group>
                <group name="group7">
                  <group
                    name="group5"
                    position={[6.082, 8.281, -6.608]}
                    rotation={[-0.017, 0.047, 0.354]}>
                    <group name="pTorus8" position={[-6.082, -8.281, 6.608]}>
                      <mesh
                        name="pTorus8_base_cromogris_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.pTorus8_base_cromogris_0.geometry}
                        material={materials.base_cromogris}
                      />
                    </group>
                    <group name="pSphere16" position={[-6.082, -8.281, 6.608]}>
                      <mesh
                        name="pSphere16_rosa_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.pSphere16_rosa_0.geometry}
                        material={materials.rosa}
                      />
                    </group>
                  </group>
                </group>
                <group name="group8">
                  <group
                    name="group4"
                    position={[6.075, 8.279, -6.545]}
                    rotation={[0.035, -0.095, 0.355]}>
                    <group name="pSphere11" position={[-6.075, -8.279, 6.545]}>
                      <mesh
                        name="pSphere11_rosa_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.pSphere11_rosa_0.geometry}
                        material={materials.rosa}
                      />
                    </group>
                    <group name="pSphere15" position={[-6.075, -8.279, 6.545]}>
                      <mesh
                        name="pSphere15_azul2_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.pSphere15_azul2_0.geometry}
                        material={materials.azul2}
                      />
                    </group>
                    <group name="pTorus6" position={[-6.075, -8.279, 6.545]}>
                      <mesh
                        name="pTorus6_base_cromogris_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.pTorus6_base_cromogris_0.geometry}
                        material={materials.base_cromogris}
                      />
                    </group>
                    <group name="pSphere10" position={[-6.075, -8.279, 6.545]}>
                      <mesh
                        name="pSphere10_azul_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.pSphere10_azul_0.geometry}
                        material={materials.azul}
                      />
                    </group>
                    <group name="pSphere13" position={[-6.075, -8.279, 6.545]}>
                      <mesh
                        name="pSphere13_azul2_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.pSphere13_azul2_0.geometry}
                        material={materials.azul2}
                      />
                    </group>
                  </group>
                </group>
                <group name="group9">
                  <group
                    name="group3"
                    position={[6.084, 8.263, -6.647]}
                    rotation={[0.127, -0.331, 0.374]}>
                    <group name="pSphere18" position={[-6.084, -8.263, 6.647]}>
                      <mesh
                        name="pSphere18_rosa_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.pSphere18_rosa_0.geometry}
                        material={materials.rosa}
                      />
                    </group>
                    <group name="pTorus5" position={[-6.084, -8.263, 6.647]}>
                      <mesh
                        name="pTorus5_base_cromogris_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.pTorus5_base_cromogris_0.geometry}
                        material={materials.base_cromogris}
                      />
                    </group>
                    <group name="pSphere17" position={[-6.084, -8.263, 6.647]}>
                      <mesh
                        name="pSphere17_azul2_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.pSphere17_azul2_0.geometry}
                        material={materials.azul2}
                      />
                    </group>
                    <group name="pSphere12" position={[-6.084, -8.263, 6.647]}>
                      <mesh
                        name="pSphere12_azul_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.pSphere12_azul_0.geometry}
                        material={materials.azul}
                      />
                    </group>
                    <group name="pSphere14" position={[-6.084, -8.263, 6.647]}>
                      <mesh
                        name="pSphere14_rosa_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.pSphere14_rosa_0.geometry}
                        material={materials.rosa}
                      />
                    </group>
                  </group>
                </group>
                <group name="group10" position={[6.088, 8.279, -6.656]} rotation={[0, 0, 0.353]}>
                  <group name="pTorus9" position={[-6.088, -8.279, 6.656]}>
                    <mesh
                      name="pTorus9_base_cromogris_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.pTorus9_base_cromogris_0.geometry}
                      material={materials.base_cromogris}
                    />
                  </group>
                  <group name="pCylinder5" position={[-6.088, -8.279, 6.656]}>
                    <mesh
                      name="pCylinder5_base_cromogris_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.pCylinder5_base_cromogris_0.geometry}
                      material={materials.base_cromogris}
                    />
                  </group>
                </group>
                <group name="group11" position={[0, -0.254, 0]}>
                  <group name="pTorus10">
                    <mesh
                      name="pTorus10_base_cromogris_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.pTorus10_base_cromogris_0.geometry}
                      material={materials.base_cromogris}
                    />
                  </group>
                  <group name="pSphere19" position={[6.086, 8.55, -11.795]} scale={0.158}>
                    <mesh
                      name="pSphere19_base_cromogris_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.pSphere19_base_cromogris_0.geometry}
                      material={materials.base_cromogris}
                    />
                  </group>
                  <group
                    name="pCylinder9"
                    position={[6.089, 8.546, -11.34]}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={0.079}>
                    <mesh
                      name="pCylinder9_base_cromogris_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.pCylinder9_base_cromogris_0.geometry}
                      material={materials.base_cromogris}
                    />
                  </group>
                  <group
                    name="pPipe1"
                    position={[6.089, 8.545, -11.465]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.158}>
                    <mesh
                      name="pPipe1_base_cromogris_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.pPipe1_base_cromogris_0.geometry}
                      material={materials.base_cromogris}
                    />
                  </group>
                  <group
                    name="pCylinder10"
                    position={[6.078, 8.546, -1.937]}
                    rotation={[-Math.PI / 2, 0, Math.PI]}
                    scale={0.079}>
                    <mesh
                      name="pCylinder10_base_cromogris_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.pCylinder10_base_cromogris_0.geometry}
                      material={materials.base_cromogris}
                    />
                  </group>
                  <group
                    name="pPipe2"
                    position={[6.077, 8.545, -1.812]}
                    rotation={[Math.PI / 2, 0, -Math.PI]}
                    scale={0.158}>
                    <mesh
                      name="pPipe2_base_cromogris_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.pPipe2_base_cromogris_0.geometry}
                      material={materials.base_cromogris}
                    />
                  </group>
                  <group
                    name="pSphere20"
                    position={[6.08, 8.55, -1.482]}
                    rotation={[-Math.PI, 0, -Math.PI]}
                    scale={0.158}>
                    <mesh
                      name="pSphere20_base_cromogris_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.pSphere20_base_cromogris_0.geometry}
                      material={materials.base_cromogris}
                    />
                  </group>
                </group>
                <group name="pCylinder13" position={[6.09, 3.377, -6.625]} scale={0.802}>
                  <mesh
                    name="pCylinder13_lambert1_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCylinder13_lambert1_0.geometry}
                    material={materials.lambert1}
                  />
                </group>
                <group name="pCylinder14" position={[6.09, 2.182, -6.625]} scale={2.054}>
                  <mesh
                    name="pCylinder14_lambert1_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCylinder14_lambert1_0.geometry}
                    material={materials.lambert1}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/pendulum.gltf')
