/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type PendulumProps = {
  position: [number, number, number]
  rotation: [number, number, number]
  scale: number
}


type GLTFResult = GLTF & {
  nodes: {
    pCylinder5_base_cromogris_0: THREE.Mesh
    pTorus9_base_cromogris_0: THREE.Mesh
    pCylinder10_base_cromogris_0: THREE.Mesh
    pCylinder9_base_cromogris_0: THREE.Mesh
    pPipe1_base_cromogris_0: THREE.Mesh
    pPipe2_base_cromogris_0: THREE.Mesh
    pSphere19_base_cromogris_0: THREE.Mesh
    pSphere20_base_cromogris_0: THREE.Mesh
    pTorus10_base_cromogris_0: THREE.Mesh
    pSphere16_rosa_0: THREE.Mesh
    pTorus8_base_cromogris_0: THREE.Mesh
    pSphere10_azul_0: THREE.Mesh
    pSphere11_rosa_0: THREE.Mesh
    pSphere13_azul2_0: THREE.Mesh
    pSphere15_azul2_0: THREE.Mesh
    pTorus6_base_cromogris_0: THREE.Mesh
    pSphere12_azul_0: THREE.Mesh
    pSphere14_rosa_0: THREE.Mesh
    pSphere17_azul2_0: THREE.Mesh
    pSphere18_rosa_0: THREE.Mesh
    pTorus5_base_cromogris_0: THREE.Mesh
    pCylinder13_lambert1_0: THREE.Mesh
    pCylinder14_lambert1_0: THREE.Mesh
    pSphere9_azul2_0: THREE.Mesh
  }
  materials: {
    base_cromogris: THREE.MeshStandardMaterial
    rosa: THREE.MeshStandardMaterial
    azul: THREE.MeshStandardMaterial
    azul2: THREE.MeshStandardMaterial
    lambert1: THREE.MeshStandardMaterial
  }
}

type ActionName = 'Take 001'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

export function Pendulum({position, rotation, scale}: PendulumProps) {
  const group = useRef<THREE.Object3D[]>([]);
  const { nodes, materials, animations } = useGLTF('/untitled.gltf') as GLTFResult
  const { actions } = useAnimations<GLTFActions>(animations, group)
  
  useEffect(() => {
    if (actions['Take 001']) {
      actions['Take 001'].play()
      actions['Take 001'].setLoop(THREE.LoopRepeat, Infinity)
    }
  }, [actions])
  
  return (
    <group ref={group} position={position} rotation={rotation} scale={scale} dispose={null}>
      <group name="Scene">
        <group
          name="Sketchfab_model"
          position={[-5.58, -0.399, 7.01]}
          rotation={[-Math.PI / 2, 0, 0]}>
          <group name="1460ccfda89e4dd5a93ef6862d8e1a90fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="group10" position={[6.088, 8.279, -6.656]}>
                  <group name="pCylinder5" position={[-6.088, -8.279, 6.656]}>
                    <mesh
                      name="pCylinder5_base_cromogris_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.pCylinder5_base_cromogris_0.geometry}

                    >
                      <meshStandardMaterial
                        {...materials.base_cromogris}
                        metalness={1}
                        roughness={0.2}
                        envMapIntensity={1}
                      />
                    </mesh>
                  </group>
                  <group name="pTorus9" position={[-6.088, -8.279, 6.656]}>
                    <mesh
                      name="pTorus9_base_cromogris_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.pTorus9_base_cromogris_0.geometry}
                    >
                      <meshStandardMaterial
                        {...materials.base_cromogris}
                        metalness={1}
                        roughness={0.2}
                        envMapIntensity={1}
                      />
                    </mesh>
                  </group>
                </group>
                <group name="group11" position={[0, -0.254, 0]}>
                  <group
                    name="pCylinder10"
                    position={[6.078, 8.546, -1.937]}
                    rotation={[-Math.PI / 2, 0, Math.PI]}
                    scale={0.079}>
                    <mesh
                      name="pCylinder10_base_cromogris_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.pCylinder10_base_cromogris_0.geometry}
                      material={materials.base_cromogris}
                    />
                  </group>
                  <group
                    name="pCylinder9"
                    position={[6.089, 8.546, -11.34]}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={0.079}>
                    <mesh
                      name="pCylinder9_base_cromogris_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.pCylinder9_base_cromogris_0.geometry}
                    >
                      <meshStandardMaterial
                        {...materials.base_cromogris}
                        metalness={1}
                        roughness={0.2}
                        envMapIntensity={1}
                      />
                    </mesh>
                  </group>
                  <group
                    name="pPipe1"
                    position={[6.089, 8.545, -11.465]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.158}>
                    <mesh
                      name="pPipe1_base_cromogris_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.pPipe1_base_cromogris_0.geometry}
                    >
                      <meshStandardMaterial
                        {...materials.base_cromogris}
                        metalness={1}
                        roughness={0.2}
                        envMapIntensity={1}
                      />
                    </mesh>
                  </group>
                  <group
                    name="pPipe2"
                    position={[6.077, 8.545, -1.812]}
                    rotation={[Math.PI / 2, 0, -Math.PI]}
                    scale={0.158}>
                    <mesh
                      name="pPipe2_base_cromogris_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.pPipe2_base_cromogris_0.geometry}
                    >
                      <meshStandardMaterial
                        {...materials.base_cromogris}
                        metalness={1}
                        roughness={0.2}
                        envMapIntensity={1}
                      />
                    </mesh>
                  </group>
                  <group name="pSphere19" position={[6.086, 8.55, -11.795]} scale={0.158}>
                    <mesh
                      name="pSphere19_base_cromogris_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.pSphere19_base_cromogris_0.geometry}
                    >
                      <meshStandardMaterial
                        {...materials.base_cromogris}
                        metalness={1}
                        roughness={0.2}
                        envMapIntensity={1}
                      />
                    </mesh>
                  </group>
                  <group
                    name="pSphere20"
                    position={[6.08, 8.55, -1.482]}
                    rotation={[-Math.PI, 0, -Math.PI]}
                    scale={0.158}>
                    <mesh
                      name="pSphere20_base_cromogris_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.pSphere20_base_cromogris_0.geometry}
                    >
                      <meshStandardMaterial
                        {...materials.base_cromogris}
                        metalness={1}
                        roughness={0.2}
                        envMapIntensity={1}
                      />
                    </mesh>
                  </group>
                  <group name="pTorus10">
                    <mesh
                      name="pTorus10_base_cromogris_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.pTorus10_base_cromogris_0.geometry}

                    >
                      <meshStandardMaterial
                        {...materials.base_cromogris}
                        metalness={1}
                        roughness={0.2}
                        envMapIntensity={1}
                      />
                    </mesh>
                  </group>
                </group>
                <group name="group7">
                  <group name="group5" position={[6.082, 8.281, -6.608]}>
                    <group name="pSphere16" position={[-6.082, -8.281, 6.608]}>
                      <mesh
                        name="pSphere16_rosa_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.pSphere16_rosa_0.geometry}
                        material={materials.rosa}
                      />
                    </group>
                    <group name="pTorus8" position={[-6.082, -8.281, 6.608]}>
                      <mesh
                        name="pTorus8_base_cromogris_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.pTorus8_base_cromogris_0.geometry}
                        material={materials.base_cromogris}
                      />
                    </group>
                  </group>
                </group>
                <group name="group8">
                  <group name="group4" position={[6.075, 8.279, -6.545]}>
                    <group name="pSphere10" position={[-6.075, -8.279, 6.545]}>
                      <mesh
                        name="pSphere10_azul_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.pSphere10_azul_0.geometry}
                        material={materials.azul}
                      />
                    </group>
                    <group name="pSphere11" position={[-6.075, -8.279, 6.545]}>
                      <mesh
                        name="pSphere11_rosa_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.pSphere11_rosa_0.geometry}
                        material={materials.rosa}
                      />
                    </group>
                    <group name="pSphere13" position={[-6.075, -8.279, 6.545]}>
                      <mesh
                        name="pSphere13_azul2_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.pSphere13_azul2_0.geometry}
                        material={materials.azul2}
                      />
                    </group>
                    <group name="pSphere15" position={[-6.075, -8.279, 6.545]}>
                      <mesh
                        name="pSphere15_azul2_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.pSphere15_azul2_0.geometry}
                        material={materials.azul2}
                      />
                    </group>
                    <group name="pTorus6" position={[-6.075, -8.279, 6.545]}>
                      <mesh
                        name="pTorus6_base_cromogris_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.pTorus6_base_cromogris_0.geometry}
                        material={materials.base_cromogris}
                      />
                    </group>
                  </group>
                </group>
                <group name="group9">
                  <group name="group3" position={[6.084, 8.263, -6.647]}>
                    <group name="pSphere12" position={[-6.084, -8.263, 6.647]}>
                      <mesh
                        name="pSphere12_azul_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.pSphere12_azul_0.geometry}
                        material={materials.azul}
                      />
                    </group>
                    <group name="pSphere14" position={[-6.084, -8.263, 6.647]}>
                      <mesh
                        name="pSphere14_rosa_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.pSphere14_rosa_0.geometry}
                        material={materials.rosa}
                      />
                    </group>
                    <group name="pSphere17" position={[-6.084, -8.263, 6.647]}>
                      <mesh
                        name="pSphere17_azul2_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.pSphere17_azul2_0.geometry}
                        material={materials.azul2}
                      />
                    </group>
                    <group name="pSphere18" position={[-6.084, -8.263, 6.647]}>
                      <mesh
                        name="pSphere18_rosa_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.pSphere18_rosa_0.geometry}
                        material={materials.rosa}
                      />
                    </group>
                    <group name="pTorus5" position={[-6.084, -8.263, 6.647]}>
                      <mesh
                        name="pTorus5_base_cromogris_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.pTorus5_base_cromogris_0.geometry}
                        material={materials.base_cromogris}
                      />
                    </group>
                  </group>
                </group>
                <group name="pCylinder13" position={[6.09, 3.377, -6.625]} scale={0.802}>
                  <mesh
                    name="pCylinder13_lambert1_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCylinder13_lambert1_0.geometry}
                    material={materials.lambert1}
                  />
                </group>
                <group name="pCylinder14" position={[6.09, 2.182, -6.625]} scale={2.054}>
                  <mesh
                    name="pCylinder14_lambert1_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCylinder14_lambert1_0.geometry}
                    material={materials.lambert1}
                  />
                </group>
                <group name="pSphere9">
                  <mesh
                    name="pSphere9_azul2_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pSphere9_azul2_0.geometry}
                    material={materials.azul2}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/untitled.gltf')